nodemcu I2c interface
cznewt/robophery pull request #15
Opened 2017-03-13 15:01 UTC by MatoKafkac

2017-03-15 13:35 UTC, MatoKafkac commented
Tak tu je gpio nastrel. Nieje otestovany ani lne dokonceny pretoze tie detect eventy budu troska komplikovanejsie.

Dolezite body na diskuziu:

1. V GpioInterfacu je novy dictionary "pins" kde key je id pinu a value bude zalezat na platforme. Bud bude objekt Pin u nodemcu alebo to bude len nejaky defaultny string. Toto pole bude teda urcovat co za piny sa pouzivaju. To sa bude ziskavat funkciov get_pin() co ti vrati bud dany objekt alebo len info ze dany pin existuje v dictionary
2. NodemcuI2cInterface ma teraz v konstruktore ako parameter instanciu NodemcuGpioInterfacu. Tot nutne aby sa vytvorili dane objekty a zarezervovali sa dane piny. Tu teda pri vytvarani I2cInterfacu uz bude musiet pred tym existovat GpioInterface. Rozmyslal som ze toto by mohlo byt vlastne v kazdom I2cInterfacu a minimalne by sa rezervovali piny ze su uz pouzite. Tzn ze by aj BBB mal i2c interface ktory by v konstruktore len zarezervoval piny ktore sa pozivaju (bus2 je napr P9_19,20) a dalej volal konstruktor SMBusInterfacu

2017-03-15 16:40 UTC, cznewt requested changes
Perfect minor issues to fix

2017-03-15 16:40 UTC, cznewt commented on robophery/platform/nodemcu/gpio.py
> +                               self.GPIO_EVENT_BITH: Pin.IRQ_FALLING|Pin.IRQ_RISING }
BITH > BOTH

2017-03-15 16:40 UTC, cznewt commented on robophery/platform/nodemcu/gpio.py
> +        pins[pin] = Pin(pin,
self._pins

2017-03-15 16:40 UTC, cznewt commented on robophery/platform/nodemcu/gpio.py
> +            return pins[pin]
self._pins

2017-03-15 16:40 UTC, cznewt commented on robophery/platform/nodemcu/gpio.py
> +            return 'None'
exception? it should not ever happen or just None

2017-03-15 16:40 UTC, cznewt commented on robophery/platform/nodemcu/gpio.py
> +        self.pins[pin].irq(handler=callback,
_pins

2017-03-15 16:40 UTC, cznewt commented on robophery/platform/nodemcu/gpio.py
> +        self.pins[pin].irq()
_pins

2017-03-15 16:40 UTC, cznewt commented on robophery/platform/nodemcu/gpio.py
> +        return [self.pins[pin].value() for pin in pins]
_pins

2017-03-22 21:55 UTC, cznewt approved these changes

2017-03-31 18:23 UTC, merged